### ISSUE TITLE
Feature request: Weaponcore Support

### ISSUE THREAD

**Issue by kontu** [THDigi/BuildInfo#1]
Right now weaponcore weapons don't report stats in buildinfo, it just says "WeaponCore block, no stats available"

It would be super awesome if buildinfo was able to integrate to support pulling stats from the WeaponCore API so that it could properly display them, as weaponcore seems to be gaining more traction in the MP environment

https://i.imgur.com/IdJALYG.png

**Comment by THDigi** [comment]
There's too much complexity to machine-generate something readable. What you see in the screenshot is the actual support, to not show vanilla ammo stats for WC weapons because they would be useless and misleading (all zeroes).

WC modders should write the important stats in their block description and players can see that without this mod :P
