### ISSUE TITLE
Toolbar info empty and toolbarlabel no longer working

### ISSUE THREAD

**Issue by Squeech007** [THDigi/BuildInfo#8]
stopped working since update, since sigma draconis server just updated now from signal to recent version i only notice this now

After some testing i noticed that the programmable block may be the issue. Adding an action via g-menu now adds another input screen for a "label" (which is a cool idea but limited to certain amount of characters". this label will overwrite the mod completly in that area and info toolbar is not capable af handling that

![Unbenannt2](https://github.com/user-attachments/assets/91c172d4-6637-4a77-bd09-7e9cf4156abb)

toolbar 4-5 : i changed the pb and forced to add a label "thrustra" (no more letters allowed). buildinfo as seen on the right side did not update and still shows the old info. (all other bars are from before the update)

if i add pb to the empty spot, toolbar info will also not update and simply stay empty.

**Comment by THDigi** [comment]
The prompt for a label is game's own feature added in SE v205, it's also on the new rotor and piston actions.

I currently have a mess of 2 systems for handling toolbars (one for cockpits and other for literally any other toolbar) so I need to unify those in order to populate it with the new label feature.

And it's gonna be confusing with labels being shown in _status_ area by the game and then I'm trying to show actual status there... more messes.
